env = "online"
debug = true

[database]
driver = "sqlite3" # sqlite3, mysql, postgres
host = ""
port = 0
username = ""
password = ""
database = "app.db"
show_sql = true

[web]
listen_addr = "127.0.0.1:3000"